services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway
    container_name: gateway
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: gateway
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./gateway:/var/www
      - ./gateway/docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - alegra-network
    depends_on:
      - gatewayDB

  gatewayDB:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - alegra-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./gateway:/var/www
      - ./gateway/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - alegra-network
    depends_on:
      - gateway

  warehouse:
    build:
      context: ./warehouse
      dockerfile: Dockerfile
    image: warehouse
    container_name: warehouse
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: warehouse
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./warehouse:/var/www
      - ./warehouse/docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./warehouse/var/log/supervisor:/var/log/supervisor
    networks:
      - alegra-network
    depends_on:
      - warehouseDB

  warehouseDB:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - warehousedbdata:/var/lib/mysql
    networks:
      - alegra-network

  warehouseWebserver:
    image: nginx:alpine
    container_name: warehouse-webserver
    restart: unless-stopped
    volumes:
      - ./warehouse:/var/www
      - ./warehouse/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - alegra-network
    depends_on:
      - warehouse

  kitchen:
    build:
      context: ./kitchen
      dockerfile: Dockerfile
    image: kitchen
    container_name: kitchen
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: kitchen
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./kitchen:/var/www
      - ./kitchen/docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - alegra-network
    depends_on:
      - kitchenDB

  kitchenDB:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kitchen
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - kitchendbdata:/var/lib/mysql
    networks:
      - alegra-network

  kitchenWebserver:
    image: nginx:alpine
    container_name: kitchen-webserver
    restart: unless-stopped
    volumes:
      - ./kitchen:/var/www
      - ./kitchen/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - alegra-network

networks:
  alegra-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  warehousedbdata:
    driver: local
  kitchendbdata:
    driver: local